import { BRAND } from './brand';

const colors = {
  light: {
    background: BRAND.background,
    foreground: BRAND.text,
    card: BRAND.surface,
    cardForeground: BRAND.text,
    primary: BRAND.primary,
    primaryForeground: '#FFFFFF',
    secondary: BRAND.primaryLight,
    secondaryForeground: BRAND.primary,
    muted: BRAND.primaryLight,
    mutedForeground: BRAND.textMuted,
    accent: BRAND.gold,
    accentForeground: BRAND.text,
    destructive: BRAND.destructive,
    destructiveForeground: '#FFFFFF',
    border: BRAND.border,
    input: BRAND.border,
    text: BRAND.text,
    tint: BRAND.primary,
  },
  dark: {
    background: '#12101A',
    foreground: '#F5F3FA',
    card: '#1E1A28',
    cardForeground: '#F5F3FA',
    primary: '#9B7FD4',
    primaryForeground: '#FFFFFF',
    secondary: '#2A2040',
    secondaryForeground: '#C4B5E8',
    muted: '#2A2040',
    mutedForeground: '#A89BBF',
    accent: BRAND.gold,
    accentForeground: BRAND.text,
    destructive: '#FF6B6B',
    destructiveForeground: '#FFFFFF',
    border: '#3D3550',
    input: '#3D3550',
    text: '#F5F3FA',
    tint: '#9B7FD4',
  },
  radius: 12,
};
export default colors;
