const colors = {
  light: {
    background: '#F4F4F4',
    foreground: '#2C2C2C',
    card: '#FFFFFF',
    cardForeground: '#2C2C2C',
    primary: '#FF3B30',
    primaryForeground: '#FFFFFF',
    secondary: '#FFF0EF',
    secondaryForeground: '#FF3B30',
    muted: '#F0F0F0',
    mutedForeground: '#717171',
    accent: '#3D1A78',
    accentForeground: '#FFFFFF',
    destructive: '#C0392B',
    destructiveForeground: '#FFFFFF',
    border: '#E8E8E8',
    input: '#E8E8E8',
    text: '#2C2C2C',
    tint: '#FF3B30',
  },
  dark: {
    background: '#121212',
    foreground: '#F5F5F5',
    card: '#1E1E1E',
    cardForeground: '#F5F5F5',
    primary: '#FF453A',
    primaryForeground: '#FFFFFF',
    secondary: '#2A1514',
    secondaryForeground: '#FF453A',
    muted: '#2A2A2A',
    mutedForeground: '#A0A0A0',
    accent: '#9B7FD4',
    accentForeground: '#FFFFFF',
    destructive: '#FF453A',
    destructiveForeground: '#FFFFFF',
    border: '#333333',
    input: '#333333',
    text: '#F5F5F5',
    tint: '#FF453A',
  },
  radius: 12,
};
export default colors;
