/** Varsayılan uygulama yapılandırması — admin panelden üzerine yazılabilir */

export const DEFAULT_APP_CONFIG: Record<string, unknown> = {
  "brand": {
    name: "Pazaryeri",
    tagline: "Türkiye'nin ikinci el alım satım platformu",
    primary: "#3D1A78",
    primaryDark: "#2A1260",
    primaryMid: "#5B3FA0",
    primaryLight: "#F4F1FA",
    gold: "#C9A84C",
    background: "#F7F5FC",
    supportEmail: "pazaryer0@gmail.com",
    assets: {
      iconUrl: null,
      logoUrl: null,
      splashUrl: null,
      faviconUrl: null,
      ogImageUrl: null,
      adaptiveIconUrl: null,
    },
  },
  "web.seo": {
    brand: "Pazaryeri",
    tagline: "Türkiye'nin ikinci el alım satım platformu",
    title: "Pazaryeri — İkinci El Alım Satım | Ücretsiz İlan Ver",
    description:
      "Pazaryeri ile ücretsiz ilan verin, ikinci el alım satım yapın. Telefon, araç, mobilya, elektronik ve binlerce kategoride güvenli ikinci el alışveriş.",
    keywords:
      "pazaryeri, ikinci el, ücretsiz ilan, alım satım, ikinci el telefon, ikinci el araba",
  },
  "web.announcements": [],
  "mobile.categories": [
    "Tümü",
    "Elektronik",
    "Telefon",
    "Bilgisayar",
    "Araç",
    "Emlak",
    "Mobilya",
    "Ev & Bahçe",
    "Moda",
    "Spor",
    "Bebek",
    "Hobi",
    "İş & Ofis",
    "Hayvanlar",
    "Müzik",
    "Beyaz Eşya",
    "Kozmetik",
    "Antika",
    "Diğer",
  ],
  "mobile.featureFlags": {
    enableOffers: true,
    enableComments: true,
    enablePush: true,
    enableLocationFilter: true,
    maintenanceMode: false,
    maintenanceMessage: "Bakım çalışması yapılıyor. Kısa süre sonra tekrar deneyin.",
  },
  "mobile.app": {
    name: "Pazaryeri",
    version: "1.0.0",
    minSupportedVersion: "1.0.0",
    forceUpdate: false,
    updateMessage: "Yeni sürüm mevcut. Lütfen güncelleyin.",
  },
  "mobile.developer": {
    enabled: true,
    signatureLabel: "dev/ByAltun",
    rateApp: {
      enabled: true,
      label: "Uygulamayı Puanla & Yorumla",
      androidUrl: "https://play.google.com/store/apps/details?id=com.pazaryerim",
      iosUrl: null,
      webUrl: "https://play.google.com/store/apps/details?id=com.pazaryerim",
    },
    otherApps: {
      enabled: true,
      label: "Yapımcının Diğer Uygulamaları",
      url: "https://play.google.com/store/apps/developer?id=By+Altun",
    },
  },
  "mobile.sponsorBanner": {
    enabled: false,
    imageUrl: null,
    linkUrl: null,
    altText: "Sponsor",
  },
  "mobile.sponsorBanners": [
    { placement: "home", enabled: false, imageUrl: null, linkUrl: null, altText: "Sponsor" },
    { placement: "explore", enabled: false, imageUrl: null, linkUrl: null, altText: "Sponsor" },
    { placement: "post", enabled: false, imageUrl: null, linkUrl: null, altText: "Sponsor" },
    { placement: "messages", enabled: false, imageUrl: null, linkUrl: null, altText: "Sponsor" },
    { placement: "profile", enabled: false, imageUrl: null, linkUrl: null, altText: "Sponsor" },
    { placement: "listing", enabled: false, imageUrl: null, linkUrl: null, altText: "Sponsor" },
    { placement: "web", enabled: false, imageUrl: null, linkUrl: null, altText: "Sponsor" },
  ],
  "mobile.admob": {
    testMode: true,
    banner: {
      enabled: false,
      androidAppId: "ca-app-pub-3940256099942544~3347511713",
      iosAppId: "ca-app-pub-3940256099942544~1458002511",
      androidUnitId: "ca-app-pub-3940256099942544/6300978111",
      iosUnitId: "ca-app-pub-3940256099942544/2934735716",
    },
    interstitial: {
      enabled: false,
      androidAppId: "ca-app-pub-3940256099942544~3347511713",
      iosAppId: "ca-app-pub-3940256099942544~1458002511",
      androidUnitId: "ca-app-pub-3940256099942544/1033173712",
      iosUnitId: "ca-app-pub-3940256099942544/4411468910",
      thirdSessionEnabled: true,
      afterSecondListingEnabled: true,
      afterDeleteListingEnabled: true,
    },
    rewarded: {
      enabled: false,
      androidAppId: "ca-app-pub-3940256099942544~3347511713",
      iosAppId: "ca-app-pub-3940256099942544~1458002511",
      androidUnitId: "ca-app-pub-3940256099942544/5224354917",
      iosUnitId: "ca-app-pub-3940256099942544/1712485313",
      boostHours: 2,
    },
  },
  "web.appDownload": {
    enabled: true,
    title: "Mobil Uygulamamızı İndirin",
    subtitle: "Daha hızlı ilan ver, anında mesajlaş",
    buttonText: "Uygulamayı İndir",
    androidStoreUrl: "https://play.google.com/store/apps/details?id=com.pazaryerim",
    iosStoreUrl: "https://apps.apple.com/app/id0000000000",
    androidDeepLink: "pazaryeri://",
    iosDeepLink: "pazaryeri://",
    showOnDesktop: false,
  },
};

export const CONFIG_KEYS = Object.keys(DEFAULT_APP_CONFIG);
